0.9.0 prerelease
Devolutions/devolutions-crypto pull request #290
Opened 2023-06-15 12:43 UTC by MathieuMorrissette

StaticSecret::from is broken the output is never the same.

2023-07-10 20:05 UTC, pdugre requested changes

2023-07-10 20:05 UTC, pdugre commented on devolutions-crypto/src/utils.rs
> +    let _ = pbkdf2::<Hmac<Sha256>>(key, salt, iterations, &mut new_key);
See above

2023-07-12 02:02 UTC, sduquette-devolutions commented
svp aviser @LucFauvel quand la release sera faite, il a besoin du changement suivant. merci!
https://github.com/Devolutions/devolutions-crypto/pull/289

2023-07-12 13:17 UTC, MathieuMorrissette commented on devolutions-crypto/src/ciphertext/ciphertext_v1.rs
> +        let _ = pbkdf2::<Hmac<Sha256>>(secret, &salt[0..1], 1, encryption_key);
this was to fix a clippy warning

2023-07-12 13:17 UTC, MathieuMorrissette commented on devolutions-crypto/src/ciphertext/ciphertext_v1.rs
> +        let _ = pbkdf2::<Hmac<Sha256>>(secret, &salt[0..1], 1, signature_key);
this was to fix a clippy warning

2023-07-12 13:19 UTC, MathieuMorrissette commented on devolutions-crypto/src/ffi.rs
> +    }
used in a test case only that use only padded base64
https://github.com/Devolutions/devolutions-crypto/pull/290/files#diff-d7b4d32aa195b36d844832f97ba450f66439d2d4505f6b1f2fd87d436ac5465aR1368-R1384

2023-07-12 13:19 UTC, MathieuMorrissette commented on devolutions-crypto/src/utils.rs
> +    let _ = pbkdf2::<Hmac<Sha256>>(key, salt, iterations, &mut new_key);
this was to fix a clippy warning

2023-07-12 13:48 UTC, MathieuMorrissette commented
> svp aviser @LucFauvel quand la release sera faite, il a besoin du changement suivant. merci! #289

Nous allons faire une 0.8.1 parce que dans cette pull, nous utilisons des crates de crypto qui sont toujours en Release Candidate : 
ed25519-dalek = { version = "2.0.0-rc.3", features = [ "rand_core" ] }
x25519-dalek = { version = "2.0.0-rc.3", features = [ "static_secrets" ] }

2023-08-23 14:15 UTC, pdugre approved these changes

2023-08-23 15:26 UTC, Sylfwood requested changes
Ca semble fonctionner sans, mais comme c'est du YAML, ca serait mieux de mettre les `|` sur du multiline pour le `run:`

2023-08-23 15:26 UTC, richerlariviere submitted a review, later dismissed

2023-08-23 15:27 UTC, Sylfwood commented on .github/workflows/python/build/macos/action.yml
> +        source $HOME/.cargo/env
Si vous travailler sur VS Code, l'extension Github Actions est un must 
<img width="799" alt="Screenshot 2023-08-23 at 11 26 53 AM" src="https://github.com/Devolutions/devolutions-crypto/assets/54908935/5ce43af3-e5c3-4eb0-b492-15a0cf8b5557">

2023-08-23 15:30 UTC, Sylfwood approved these changes

2023-08-23 16:18 UTC, merged