[WIP] Release workflow for NPM, Python, Crates.io
Devolutions/devolutions-crypto pull request #298
Opened 2023-08-30 13:23 UTC by MathieuMorrissette

2023-08-31 12:47 UTC, pdugre requested changes

2023-08-31 12:47 UTC, pdugre commented on .github/workflows/release.yml
> +          npm publish --access=public
Don't forget to specify auth token

2023-10-11 16:39 UTC, dion-gionet approved these changes

2023-10-11 17:49 UTC, pdugre approved these changes

2023-10-11 17:50 UTC, merged